---
# syntax check: https://lint.travis-ci.org/

# Based on:
#  - https://www.jeffgeerling.com/blog/testing-ansible-roles-travis-ci-github
#  - http://romanvm.pythonanywhere.com/post/using-docker-travis-continuous-integration-25/
#  - https://www.jeffgeerling.com/blog/2016/how-i-test-ansible-configuration-on-7-different-oses-docker
#  - https://www.jeffgeerling.com/blog/2017/fix-ansible-hanging-when-used-docker-and-tty
#  - https://bertvv.github.io/notes-to-self/2015/12/13/testing-ansible-roles-with-travis-ci-part-2-multi-platform-tests/

language: python
cache: pip
python: "2.7"
git:
  depth: 3

sudo: required

env:
  # Stable
  - os=ubuntu version=latest container_id=$(mktemp)
  #- os=debian version=latest container_id=$(mktemp)
  # Testing
  #- os=ubuntu version=testing container_id=$(mktemp)
  #- os=debian version=testing container_id=$(mktemp)
  # Ubuntu: https://hub.docker.com/_/ubuntu/ - https://launchpad.net/ubuntu
  # Debian: https://hub.docker.com/_/debian/ - https://www.debian.org/releases/

matrix:
  fast_finish: true
  allow_failures:
    - env: os=debian
    - env: version=testing

before_install:
  - docker pull ${os}:${version}
  - docker run -d --name "$(cat ${container_id})" -v $(pwd):/travis ${os}:${version} tail -f /dev/null > "${container_id}"

install:
  - > # prepare ansible
    docker exec "$(cat ${container_id})" bash -c 'apt-get update -qq &&
      apt-get install -qqy python-pip &&
      pip install --upgrade pip &&
      pip install ansible'

before_script:
  - export ansible_command='cd /travis && ansible-playbook tomboy.yml'

script:
  - docker exec "$(cat ${container_id})" bash -c "$ansible_command --syntax-check"
  - docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 bash -c "$ansible_command"
  - >
    if [ "$TRAVIS_BRANCH" = "idempotence" ] ; then docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 bash -c "$ansible_command
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)"; fi

after_failure:
  - echo $TRAVIS_TEST_RESULT

after_script:
  - docker stop "$(cat ${container_id})"
