---
# syntax check: https://lint.travis-ci.org/
language: c
os: osx # https://docs.travis-ci.com/user/reference/osx
matrix:
  include:
    - os: osx # https://travis-ci.org/MacPython
      # thanks https://github.com/WhyNotHugo
      # https://github.com/travis-ci/travis-ci/issues/2312#issuecomment-289140791

before_install: # thanks https://github.com/andyli
  # https://github.com/travis-ci/travis-ci/issues/3448#issuecomment-250075501
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      ./bin/osx_install_pip.sh
    else if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      sudo apt-get update && sudo apt-get -y install python-pip
    fi; fi

install:
  - pip install --upgrade pip
  - pip install ansible

before_script:
  - export ansible_command='cd /travis && ansible-playbook tomboy.yml'

script:
  - $ansible_command --syntax-check
  - $ansible_command

...
