---
# syntax check: https://lint.travis-ci.org/
language: c
os: osx # https://docs.travis-ci.com/user/reference/osx
matrix:
  include:
    - os: osx # https://travis-ci.org/MacPython
      # thanks https://github.com/WhyNotHugo
      # https://github.com/travis-ci/travis-ci/issues/2312#issuecomment-289140791

before_install: # thanks https://github.com/andyli
  # https://github.com/travis-ci/travis-ci/issues/3448#issuecomment-250075501
  - |
    sw_vers
    brew update || brew update
    brew install --HEAD --without-readline --without-xz --without-gdbm --without-sqlite python3
    curl -O https://bootstrap.pypa.io/get-pip.py # 1.5mb
    python get-pip.py --user
    pyenv rehash
    python -m pip install --user virtualenv

install:
  - pip install --upgrade pip
  - pip install ansible

before_script:
  - export ansible_command='ansible-playbook tomboy.yml'

script:
  - $ansible_command --syntax-check
  - $ansible_command

...
