---
# syntax check: https://lint.travis-ci.org/

# Based on:
#  - https://www.jeffgeerling.com/blog/testing-ansible-roles-travis-ci-github
#  - http://romanvm.pythonanywhere.com/post/using-docker-travis-continuous-integration-25/
#  - https://www.jeffgeerling.com/blog/2016/how-i-test-ansible-configuration-on-7-different-oses-docker
#  - https://www.jeffgeerling.com/blog/2017/fix-ansible-hanging-when-used-docker-and-tty
#  - https://bertvv.github.io/notes-to-self/2015/12/13/testing-ansible-roles-with-travis-ci-part-2-multi-platform-tests/

language: python
cache: pip
python: "2.7"
git:
  depth: 3

os: # https://docs.travis-ci.com/user/multi-os/
  - linux
  - osx # https://docs.travis-ci.com/user/reference/osx

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.3

before_install:
  - docker pull ${os}:${version}
  - docker run -d --name "$(cat ${container_id})" -v $(pwd):/travis ${os}:${version} tail -f /dev/null > "${container_id}"

install:
  - pip install --upgrade pip
  - pip install ansible

before_script:
  - export ansible_command='cd /travis && ansible-playbook tomboy.yml'

script:
  - $ansible_command --syntax-check
  - $ansible_command

...
