---
# Ansible playbook to build Tomboy NG/Pascal with Lazarus

- hosts: localhost
  pre_tasks:
    - name: Check for Tomboy_NG binary
      stat: path=src/tomboy-ng/Tomboy_NG
      register: find_build
      tags: build

  roles:
   - { role: tomboy, when: find_build is not defined or not find_build.stat.exists }

  post_tasks:
    - name: Start src/tomboy-ng/tomboy-ng
      command: chdir=src/tomboy-ng ./tomboy-ng &
      when: not 'travis' in dir
      tags: build

...
