---
# Mac i386 https://sourceforge.net/projects/lazarus/files/Lazarus%20Mac%20OS%20X%20i386/Lazarus%201.8.0RC5/
- name: Download upstream Lazarus OSX intel packages (~150mb)
  uri: url={{item.url}} dest=cache/{{item.file}} creates=cache/{{item.file}} status_code=200,304
  with_items: # intel
   - { file: "fpc-src-3.0.2-macosx.dmg", url: "https://sourceforge.net/projects/lazarus/files/Lazarus%20Mac%20OS%20X%20i386/Lazarus%201.8.0RC5/fpc-src-3.0.2-macosx.dmg" }
   - { file: "fpc-3.0.2.intel-macosx.dmg", url: "https://sourceforge.net/projects/lazarus/files/Lazarus%20Mac%20OS%20X%20i386/Lazarus%201.8.0RC5/fpc-3.0.2.intel-macosx.dmg" }
   - { file: "lazarus-1.8.0-RC5-i686-macosx.dmg", url: "https://sourceforge.net/projects/lazarus/files/Lazarus%20Mac%20OS%20X%20i386/Lazarus%201.8.0RC5/lazarus-1.8.0-RC5-i686-macosx.dmg" }
  retries: 3

- name: Install Lazarus (Mac intel)
  shell: |
    export mountpath=/Volumes/{{item.path}}
    hdiutil mount -nobrowse cache/{{item.file}}
    hdiutil info && ls /Volumes && ls -l $mountpath && find $mountpath # uncomment for a lot of debug output
    sudo installer -pkg "$mountpath/{{item.pkg}}" #-target "/Volumes/Macintosh HD"
    hdiutil unmount "$mountpath"
  with_items:
    - { path: fpc-3.0.2.intel-macosx, file: fpc-3.0.2.intel-macosx.dmg, pkg: fpc-3.0.2.intel-macosx.pkg }
    - { path: fpcsrc-3.0.2, file: fpc-src-3.0.2-macosx.dmg, pkg: fpcsrc-3.0.2.pkg }
    - { path: lazarus-1.8.05, file: lazarus-1.8.0-RC5-i686-macosx.dmg, pkg: lazarus.pkg }
  register: hdiutil
- debug: var=hdiutil # uncomment for a lot of debug output
  # mounting and installing on osx http://blog.smalleycreative.com/administration/automating-osx-part-one/
  # hdiutil manual https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/hdiutil.1.html
  # "installer: Cannot install on volume / because it is disabled.", 
  # "installer: This is the PowerPC version of the Free Pascal Compiler, while you are using an Intel Mac. Install the Intel version instead, it includes a PowerPC cross-compiler and will perform much better.", 
