---
# Install Lazarus

- name: Install dependencies
  become: yes
  package: name={{item}} state=present
  with_items: { git, tar, unzip, libgtk2.0-dev }
  tags: deps

- name: Download upstream Lazarus deb packages (~100mb)
  uri: url={{item.url}} dest=cache/{{item.file}} creates=cache/{{item.file}} status_code=200,304
  with_items:
   - { file: "fpc_3.0.4-rc1_{{ architecture }}.deb", url: "https://sourceforge.net/projects/lazarus/files/Lazarus%20Linux%20{{ architecture }}%20DEB/Lazarus%201.8.0RC5/fpc_3.0.4-rc1_{{ architecture }}.deb" }
   - { file: "fpc-src_3.0.4-rc1_{{ architecture }}.deb", url: "https://sourceforge.net/projects/lazarus/files/Lazarus%20Linux%20{{ architecture }}%20DEB/Lazarus%201.8.0RC5/fpc-src_3.0.4-rc1_{{ architecture }}.deb" }
   - { file: "lazarus-project_1.8.0RC5-0_{{ architecture }}.deb", url: "https://sourceforge.net/projects/lazarus/files/Lazarus%20Linux%20{{ architecture }}%20DEB/Lazarus%201.8.0RC5/lazarus-project_1.8.0RC5-0_{{ architecture }}.deb" }
  register: ubuntu

- name: Install Lazarus package
  become: yes
  apt: deb={{item}} state=present force=yes # we need to force as fpc and fpc_src are conflicting
  with_items: # 1.8ORC5
   - "cache/fpc_3.0.4-rc1_{{ architecture }}.deb"
   - "cache/fpc-src_3.0.4-rc1_{{ architecture }}.deb"
   - "cache/lazarus-project_1.8.0RC5-0_{{ architecture }}.deb"

...
