---
#- name: Unshallow homebrew # https://brew.sh/
#  shell: git -C "$(brew --repo homebrew/core)" fetch --unshallow

- name: Install dependencies # http://formulae.brew.sh/search/gtk
  homebrew: name=gtk+ state=present update_homebrew=yes
  tags: deps

- name: Install Lazarus
  include_tasks: "lazarus_MacOSX_{{ansible_architecture}}.yml"

...
