---

- name: Install dependencies
  package: name={{item}} state=present
  with_items: { git, tar, unzip, libgtk2.0-dev }
  tags: deps

- name: Download upstream Lazarus OSX packages (~150mb)
  uri: url={{item.url}} dest=cache/{{item.file}} creates=cache/{{item.file}} status_code=200,304
  with_items:
   - { file: "lazarus-1.2.6-powerpc-macosx.dmg", url: "https://sourceforge.net/projects/lazarus/files/Lazarus%20Mac%20OS%20X%20powerpc/Lazarus%201.2.6/lazarus-1.2.6-powerpc-macosx.dmg" }
   - { file: "fpc-2.6.4.powerpc-macosx.dmg", url: "https://sourceforge.net/projects/lazarus/files/Lazarus%20Mac%20OS%20X%20powerpc/Lazarus%201.2.6/fpc-2.6.4.powerpc-macosx.dmg" }
   - { file: "fpcsrc-2.6.4.powerpc-macosx.dmg", url: "https://sourceforge.net/projects/lazarus/files/Lazarus%20Mac%20OS%20X%20powerpc/Lazarus%201.2.6/fpcsrc-2.6.4.powerpc-macosx.dmg" }

  # TODO install on
  # Mac i386 https://sourceforge.net/projects/lazarus/files/Lazarus%20Mac%20OS%20X%20i386/
  # Mac powerpc https://sourceforge.net/projects/lazarus/files/Lazarus%20Mac%20OS%20X%20powerpc/
  # Win32 https://sourceforge.net/projects/lazarus/files/Lazarus%20Windows%2032%20bits/
  # Win64 https://sourceforge.net/projects/lazarus/files/Lazarus%20Windows%2064%20bits/

- name: Install Lazarus package
  package: deb={{item}} state=present force=yes # we need to force as fpc and fpc_src are conflicting
  with_items:
   - "cache/fpc-2.6.4.powerpc-macosx.dmg"
   - "cache/fpcsrc-2.6.4.powerpc-macosx.dmg"
   - "cache/lazarus-1.2.6-powerpc-macosx.dmg"

...
