---
# Install and build tomboy-ng - http://www.bannons.id.au/tomboy

- debug: var=ansible_user
  tags: debug
- debug: var=ansible_architecture
  tags: debug
- debug: var=ansible_distribution
  tags: debug
- debug: var=ansible_distribution_release
  tags: debug
- set_fact:
    distribution: "{{ ansible_distribution if not ansible_distribution == 'Debian' and not ansible_distribution == 'Ubuntu' else 'linux' }}"
- set_fact:
    architecture: "{{ ansible_architecture if not ansible_architecture == 'x86_64' else 'amd64' }}"

- name: Save current directory
  set_fact: dir={{ansible_env.PWD}}/src
  tags: debug, source,  build, lib, kcontrols
- name: tomboy-ng directory
  debug: var=dir
  tags: debug

- name: Create directories
  file: state=directory path={{item}}
  with_items: [ cache, lib ]

- name: Install Lazarus deps
  remote_user: "{{ ansible_user }}"
  include_tasks: lazarus_{{distribution}}.yml
  tags: [ deps, lazarus ]

- name: Clone tomboy-ng repository
  git: dest={{ dir }} repo=https://github.com/tomboy-notes/tomboy-ng  

- name: Create secondary Lazarus config dir ./lazconf
  file: state=directory path=lazconf
- name: Create ./lazconf/packagefiles.xml with links to KControls
  template: src=template/packagefiles.xml dest=lazconf/ backup=yes
  tags: [ lib, kcontrols ]

- name: Download KControls # http://www.tkweb.eu/en/delphicomp/kcontrols.html
  uri: # https://bitbucket.org/tkweb/kcontrols/downloads/
    url: https://bitbucket.org/tkweb/kcontrols/get/tip.zip
    dest: cache/KControls.zip
    creates: cache/KControls.zip
    status_code: 200,304
  tags: [ lib, kcontrols ]

- name: Extract KControls
  unarchive: 
    src: cache/KControls.zip
    dest: "{{dir}}/../lib"
    creates: "{{dir}}/../lib/tkweb-kcontrols-*"
    remote_src: yes
  register: kcontrols
  tags: [ lib, kcontrols ]

- name: Find KControls
  find: file_type=directory paths="{{dir}}/../lib" patterns='tkweb-kcontrols-*'
  register: kcontrols_dir

- name: Link KControls
  file: state=link src="{{ kcontrols_dir.files[0]['path'] }}" dest="{{dir}}/../lib/tkweb-kcontrols"

- name: Patch kgrids.pas # http://www.tkweb.eu/en/delphicomp/kcontrols.html
  patch: dest="{{dir}}/../lib/tkweb-kcontrols/source/kgrids.pas" remote_src=yes src=template/kgrids.patch backup=yes
  # To avoid:
  #   Error: (3058) There is no method in an ancestor class to be overridden:
  #    "DoAutoAdjustLayout(const TLayoutAdjustmentPolicy;const Double;const Double;const Boolean);"

- name: Build Tomboy/Pascal # cross-compiling http://wiki.freepascal.org/fpcupdeluxe
  command: chdir={{dir}}/tomboy-ng lazbuild --pcp=../../lazconf Tomboy_NG.lpi
  register: build
  ignore_errors: yes
  tags: build
- debug:
    var: build.stdout_lines
  when: build.rc != 0
  tags: build

- fail: msg="Tomboy could not be built."
  when: build.rc != 0
  tags: build

...
